# Generated by Django 2.0.9 on 2018-12-18 19:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20181218_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10)),
                ('data', models.DateTimeField(default=datetime.datetime(2018, 12, 18, 19, 48, 45, 555712))),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='empresas.Empresas')),
            ],
        ),
    ]
