# Generated by Django 2.0.9 on 2018-12-18 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_acao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 18, 20, 2, 41, 383835)),
        ),
    ]
