# Generated by Django 2.0.9 on 2018-12-18 20:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_auto_20181218_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime(2018, 12, 18, 20, 27, 40, 116465))),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='acao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 18, 20, 27, 40, 115944)),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acao', to='empresas.Acao'),
        ),
    ]
